### PR TITLE
Add support for Cohere's Command-R and Command-R+ models

### PR DESCRIPTION
**Pull request by o-mikhailovskii**
As proposed in #597, here is the PR.

### CODE REVIEW

**Comment by logancyang** [comment]
@o-mikhailovskii thanks for the PR! We probably need to move the Cohere API key setting from QA setting up to API settings then.

**Comment by logancyang** [comment]
I pulled this PR and tested, it doesn't work for me. Does it work for you?

SCR-20240908-mqec

**Comment by o-mikhailovskii** [comment]
Hey! I faced this kind of issue when trying to run with the older version of Cohere's package (and presumably the corresponding Langchain's package). That's why I updated the dependencies in the `package.json`. Have you updated the installation of the two packages?

**Comment by o-mikhailovskii** [comment]
Answering your question - yes, I am able to select and use Cohere's models.

**Comment by logancyang** [comment]
@o-mikhailovskii oh yes my bad, didn't update the package. Now it works, thanks for the contribution! I'll move the setting up myself later no worries. Merged.

**Pull request merged**
