### PR TITLE
Add Groq Implementation 

### LINKED ISSUE #430: Add Support for Groq
**Is your feature request related to a problem? Please describe.**
Add support for [Groq](www.groq.com), super cheap LPU-based LLMs

**Describe the solution you'd like**
Allow configuration to use Groq as LLM provider with API key

**Describe alternatives you've considered**
None

**Additional context**
None

### PR DESCRIPTION
**Pull request by rayxsong**
This PR adds Groq API and resolves #430.

Groq Settings

### CODE REVIEW

**Comment by rayxsong** [comment]
The secret I accidentally committed has be revoked.

**Comment by kchousos** [comment]
Any update on this?

**Comment by logancyang** [comment]
@rayxsong Thanks! Great stuff! I'll need some refactor to make this kind of changes easier in the future

**Comment by SyndicatedPillbug** [comment]
This is INCREDIBLE. It's making me giddy. Thank you!

**Pull request merged**
