### PR TITLE
Add support for GPT-4o

### PR DESCRIPTION
**Pull request by flemming-petersen**
GPT-4o was just released and it would be nice to use it in Copilot due to lower costs and faster responses.

### CODE REVIEW

**Comment by atsyplenkov** [comment]
Oh, yeah, this PR is very much anticipated! @logancyang please merge it!

**Comment by wafe** [comment]
Thank you very much for this PR!  I have directly edited my main.js. Additionally, we need to update tiktoken as well. GPT-4o uses the o200k_base tokenizer, which is different from the one used by GPT-4 models.

image

**Comment by flemming-petersen** [comment]
> Yeah great, waiting for this as well!
> 
> I believe you need to add an option to the chat model selection for it to show up:
> 
> [master...wehard:obsidian-copilot:patch-1](https://github.com/logancyang/obsidian-copilot/compare/master...wehard:obsidian-copilot:patch-1)

Thanks for your help. I have added it to my PR.

**Comment by flemming-petersen** [comment]
> Thank you very much for this PR! I have directly edited my main.js. Additionally, we need to update tiktoken as well. GPT-4o uses the o200k_base tokenizer, which is different from the one used by GPT-4 models.
> 
> image

@wafe
To my shame. I actually just looked for suitable places in the code and added the option.
Can you tell me exactly where this part needs to be added?

**Comment by peteretelej** [comment]
> @wafe To my shame. I actually just looked for suitable places in the code and added the option. Can you tell me exactly where this part needs to be added?

I'd recommend waiting for the merge. But if you have to, backup the plugin folder first. 
Just for reference for anyone that's trying to do this, the main.js output to edit is at `.obsidian/plugins/copilot/main.js`
I'd search for `GPT-4 TURBO` and add duplicate line in each of the places for `gpt-4o`. For the tokenizer, you can add a new case to the function `getEncodingNameForModel`
```
case "gpt-4o": {
      return "o200k-base";
}
```

**Comment by Richard-Woessner** [comment]
Thank you @peteretelej it worked for me

**Comment by Richard-Woessner** [comment]
[main copy.txt](https://github.com/logancyang/obsidian-copilot/files/15407500/main.copy.txt)

Also, if someone else comes across this and needs a quick reference, here's my main.js that works for me.

_I had to change it to a text file because github_

**Comment by kvndrsslr** [comment]
ℹ️ The file uploaded by @Richard-Woessner (thanks!) contains a typo so while it might look like it's working it'll actually *not* use GPT-4o. Instead it'll use whatever model you loaded before that. To fix it, search the file for `GPY-4` and replace with `GPT-4`! :)

**Comment by Richard-Woessner** [comment]
> file by @Richard-Woessner (thanks!) contains a typo so while it might look like it's working it'll actually _not_ use GPT-4o

Ope, Thanks for the heads up.

Placebo effect is real. I thought it was working lol.

**Comment by morrisjosephd** [comment]
> I'd recommend waiting for the merge. 

@peteretelej Do you have insight you can share as to when this could merge?

**Comment by peteretelej** [comment]
> > I'd recommend waiting for the merge. 
> 
> @peteretelej Do you have insight you can share as to when this could merge?

No idea, seems like Logan's been away for a while. Didn't know it'd take long. Please see my comment on how to update the main.js file to add 4o

**Comment by Richard-Woessner** [comment]
[Uploading main.copy.txt…](Fixed the typo for Everyone)

**Comment by Richard-Woessner** [comment]
[main.copy.txt Typo fixed](https://github.com/user-attachments/files/15744327/main.copy.txt)

**Comment by varlineau** [comment]
Hi! I'm sorry, I'm new to using github. How do I update my Copilot plugin to include this PR?

**Comment by Richard-Woessner** [comment]
> Hi! I'm sorry, I'm new to using github. How do I update my Copilot plugin to include this PR?

You could wait or add the main.js file yourself. I'm out so I'm not able to give a great explanation but in your vault look into the hidden .obsidian file, go to plugins, then to obsidian copilot, backup up main.js and replace it with the text file I linked.

Make sure to rename it to main.js

**Comment by varlineau** [comment]
> > Hi! I'm sorry, I'm new to using github. How do I update my Copilot plugin to include this PR?
> 
> You could wait or add the main.js file yourself. I'm out so I'm not able to give a great explanation but in your vault look into the hidden .obsidian file, go to plugins, then to obsidian copilot, backup up main.js and replace it with the text file I linked.
> 
> Make sure to rename it to main.js

Thank you so much!

**Comment by logancyang** [comment]
@flemming-petersen Sorry guys, I've been AFK for a while, life happened. But I'm back now! Thanks for the PR, merged! Will put up a new version soon!

**Pull request merged**
