### PR TITLE
Remove proxy server for LocalAI

### PR DESCRIPTION
**Pull request by Sokole1**
This PR hopes to resolve the need for a proxy server when using LocalAI as mentioned in #122.

These changes have been tested with LocalAI running with Docker and from source with my M2 Max Macbook.

# Changes
- Remove Use LocalCopilot setting
- Remove code that creates Proxy Server for LocalAI
- LocalAI Url now relies on the OpenAI Proxy Base URL setting with the value of `http://localhost:8080/v1`
- Updated documentation for how to run LocalAI with CORS enabled for local build and Docker

# Screenshot of updated Settings
image

### CODE REVIEW

**Comment by logancyang** [comment]
@Sokole1 This is awesome, thank you for your work! Merging and will push a new patch version.

**Comment by Sokole1** [comment]
Hi @logancyang it's a pleasure to have contributed to your amazing project! To answer your question about setting up a dev workflow for your plugin, it was super easy. This is actually my first exposure to developing Obsidian plugins. I followed the beginning of this video: https://www.youtube.com/watch?v=AgXa03ZxJ88&list=LL&index=4&t=4s&ab_channel=FlorianLudewig.

Then I was able to find the proxy settings in your code, got it working with :8080 and made my initial PR in little time. I didn't run into any issues.

I look forward to what's next. I saw #49 about PDFs and some mentions about a local folder to read files from. What I want is to set up "Buckets" (made up term) which consist of folders, or files to use as context. Then be able to choose a Bucket containing my Textbook PDF and relevant notes, then quickly choose which of those to include as context, such as certain chapters of my Textbook and certain notes. Is anything of this sort under development? I understand if it isn't since there are so many features but such limited time! If not, I'd be happy to open up an issue and try implementing it myself.

**Comment by logancyang** [comment]
@Sokole1 This is what I'm thinking next but haven't got time yet. The first thing for me is to get the local MemoryVectorStore to work for these more advanced use cases since LangchainJS doesn't have it yet (https://github.com/hwchase17/langchainjs/issues/1468). 

So I think these 2 can work in parallel and then pave the way to what you just described:

(1) Make embedded PDFs work for single-note QA
(2) Make local vector store work for cross-session persistence and then for multiple notes

I think (1) is a good self-contained task by itself but I haven't tried it yet. If you have time and interest you are more than welcome to explore the solution. I'm only 1 person and have other stuff to work on, so it's awesome if this project can get a great contributor like you!

**Comment by Sokole1** [comment]
Hi @logancyang thank you for your time so far. It can't be easy maintaining an open-source project. I'll gladly look into PDF QA as wanting to generate notes from my textbooks is what started my exploration into LLMs, LocalAI, and then this project. I started #125 to track any progress or findings I make. Cheers.

**Pull request merged**
