### PR TITLE
Add user custom "send notes to prompt" prompt

### PR DESCRIPTION
**Pull request by h4c5**
## Add a customizable prompt for "send notes to prompt" button #568 

This PR allow the user to customize the prompt of the "send notes to prompt" button

### CODE REVIEW

**Comment by logancyang** [comment]
@h4c5  Thanks for the PR. Actually I plan to deprecate this button. User can already pass the note by directly `[[note title]]` in the chat.

**Comment by h4c5** [comment]
Oh I see. This button is convenient in my opinion but I understand your point of view.

**Comment by logancyang** [comment]
@h4c5 IMO this button's strength was used with copilot command "set note context in chat mode" where you can specify by path or tags. But I'm going enable "ad-hoc custom prompt" inside chat directly next, so that even this use case will be covered. Thanks for the idea anyway!

**Comment by logancyang** [comment]
Closing as not planned

**Pull request closed without merging**
